### ISSUE TITLE
Cannot compile: cannot find package "github.com/jteutenberg/downpore/util/formats"

### ISSUE THREAD

**Issue by gringer** [jteutenberg/downpore#1]
I'm trying to compile the current version of downpore (cbe9e5fea7e3ef2d8e60669a364eaebe21cec00c), and it's not working for me:

```
gringer@elegans:~/install/go/src/github.com/jteutenberg/downpore$ export GOPATH="/home/gringer/install/go"
gringer@elegans:~/install/go/src/github.com/jteutenberg/downpore$ go build downpore.go 
commands/kmers.go:8:2: cannot find package "github.com/jteutenberg/downpore/util/formats" in any of:
	/usr/lib/go-1.10/src/github.com/jteutenberg/downpore/util/formats (from $GOROOT)
	/home/gringer/install/go/src/github.com/jteutenberg/downpore/util/formats (from $GOPATH)

```

I don't see 'util/formats' in the github repository. The `commands/kmers.go` code suggests there should at least be `formats.LoadSAM` and `formats.SAMAlignment`.

The v0.3.1 version compiles fine, but doesn't look like it has any SAM handling.

**Comment by gringer** [comment]
As a workaround, removing the offending lines allowed downpore to compile.

[noSAM.diff.txt](https://github.com/jteutenberg/downpore/files/1990034/noSAM.diff.txt)

**Comment by jteutenberg** [comment]
Good catch. The offending files have been committed.
