### ISSUE TITLE
trim run time error 

### ISSUE THREAD

**Issue by estolle** [jteutenberg/downpore#2]
Hi

I was just trying to run downpore to trim some ONT reads (genomic DNA, 1D basecalled).
I keep getting a runtime error, both with the precompiled and my own executable compiled from source. Any idea what the problem could be based on the error message below?

Cheers
Eckart

downpore trim -i run12/fail.fq.gz -f /opt/downpore/data/adapters_front.fasta -b /opt/downpore/data/adapters_back.fasta --himem true --num_workers 100 > run12/fail.trim.fq
2018/10/19 12:48:07 1 / 113 front adapters identified with high identity matches.
2018/10/19 12:48:07  - SQK-NSK007_Y_Top
2018/10/19 12:48:07 1 / 112 back adapters identified with high identity matches.
2018/10/19 12:48:07  - SQK-MAP006_Short_Y_Bottom_LI33
2018/10/19 12:48:07 Trimming ends and indexing all sequences against 1 adapters...
2018/10/19 12:53:54 Searching 2310844 sub-sequences for splitting based on 1 adapters
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jteutenberg/downpore/trim.(*Trimmer).Trim(0xc0001ac000, 0x5749a0, 0xc0001b2280, 0x64)
	/home/ek/go/src/github.com/jteutenberg/downpore/trim/trim.go:167 +0x15d9
github.com/jteutenberg/downpore/commands.(*trimCommand).Run(0xc00018c0c0, 0xc000182210)
	/home/ek/go/src/github.com/jteutenberg/downpore/commands/trim.go:39 +0xa6b
main.main()
	/home/ek/go/src/github.com/jteutenberg/downpore/downpore.go:86 +0xb85

**Comment by jteutenberg** [comment]
Definitely a bug of some sort.
I've committed a patch that will print a warning when this occurs and skip splitting the (invalid) sequence. Please let me know what the warning messages look like for you if possible.

Edit: actually, I believe I can see the issue. I expect there are a number of short sequences that are ineligible for splitting. I have put the fix in for the bug this caused.

**Comment by estolle** [comment]
Awesome, thanks very much. I runs without any problems now =)

**Comment by jteutenberg** [comment]
Good to hear! Thanks for reporting this.
