### ISSUE TITLE
Errors during compilation

### ISSUE THREAD

**Issue by godkin1211** [jteutenberg/downpore#3]
Hi, something gets wrong when I try to build downpore from source code:

```
# github.com/jteutenberg/downpore/commands                                                                                                                                                                         
commands/consensus.go:46:17: undefined: sequtil.LoadConfusionMatrix
```
And I cannot find such a function LoadConfucionMatrix in commands/consensus.go, either.

Could you give me any suggestions?

**Comment by jteutenberg** [comment]
This was from a commit yesterday and the patch (the missing file) was posted a couple of hours later. You must have just missed it.
Can you pull again and see if it is working for you now?

**Comment by godkin1211** [comment]
Thanks for your reply, but I still met a problem when pull and build it again:

```
# github.com/jteutenberg/downpore/trim
trim/trim.go:8:2: imported and not used: "runtime"
```

**Comment by godkin1211** [comment]
Great! I solved this problem by add comment to that line of code.

Thank you very much!

**Comment by jteutenberg** [comment]
Good to hear. I've fixed that in master now too :)
