### ISSUE TITLE
Problems with spaces in the adapter sequence identifiers 

### ISSUE THREAD

**Issue by hwalinga** [jteutenberg/downpore#5]
The adapters in the `data/` folder have sequence identifiers with spaces (e.g. `Barcode 1 (reverse)`). Since this is the name which is prepended to the header of the output files, this gives problems with further analysis. 

In general fasta/fastq files see the string of the header till the first white space character as the sequence identifier and the rest is a comment on that identifier. Some tools (e.g. `filtlong`) require the sequence identifiers to be unique (removing the comment). The alteration `downpore` makes breaks this. Now all reads have an identifier called `Barcode`. 

This is quickly patched by replacing all spaces in the `data/` files by something like underscores. However de-multiplexing is broken when you do that. 

So, would it be possible to have space free barcode names and still have all functionality `downpore` has?

**Comment by jteutenberg** [comment]
I believe that if you replace the space with anything *except* an underscore it should work. Could you try using a hypen, or just removing the space altogether?

**Comment by hwalinga** [comment]
Yes that works. But maybe change the `data/adapters_*` files so that someone doesn't have to deal with this in the future?

**Comment by jteutenberg** [comment]
That makes sense. Hyphens instead of spaces in the names now. 

All fixed until someone makes a tool that decides to delimit by hyphen.
